determiners = ["a",
               "an",
               "any",
               "anyone",
               "anything",
               "anywhere",
               "such",
               "that",
               "thats",
               "the",
               "their",
               "there",
               "theres",
               "this",
               "some",
               ]

nouns = ["address",
         "area",
         "areas",
         "barbecue",
         "belgium",
         "bistro",
         "breath",
         "center",
         "christmas",
         "city",
         "fish",
         "food",
         "foods",
         "class",
         "fusion",
         "cambridge",
         "canapes",
         "centre",
         "crossover",
         "downtown",
         "gastro",
         "gastropub",
         "east",
         "chiquito",
         "change",
         "damn",
         "care",
         "prices",
         "range",
         "restaurant",
         "restaurants",
         "rice",
         "sea",
         "seafood",
         "side",
         "something",
         "steak",
         "steakhouse",
         "system",
         "they",
         "thing",
         "time",
         "town",
         "type",
         "venue",
         "venues",
         "world",
         "you",
         "yourself",
         "south",
         "tuscan",
         "west",
         "sock",
         ]

adjectives = ["afghan",
              "african",
              "american",
              "asian",
              "australasian",
              "australian",
              "austrian",
              "basque",
              "belgian",
              "brazilian",
              "british",
              "caribbean",
              "cantonese",
              "chinese",
              "catalan",
              "cheap",
              "cuban",
              "danish",
              "english"
              "eritrean",
              "european",
              "expensive",
              "fancy",
              "fast",
              "fine",
              "french",
              "german",
              "creative",
              "corsica",
              "fusion",
              "available",
              "different",
              "central",
              "dear",
              "every",
              "else",
              "really",
              "romania",
              "romanian",
              "russian",
              "scandinavia",
              "scandinavian",
              "scottish",
              "singapore",
              "singaporean",
              "sorry",
              "spanish",
              "swedish",
              "swiss",
              "thai",
              "thailand",
              "traditional",
              "turkey",
              "turkish",
              "unusual",
              "vegetarian",
              "venetian",
              "vietnam",
              "vietnamese",
              "welsh",
              "south",
              "tuscan",
              "west",
              "surprise",
              ]

connectives = ["and",
               "but",
                "so",
               ]

#Dictionary said most verbs can be either, I mostly copied this from dictionary.com
intransitiveVerbs = ["are",
                     "am",
                     "be",
                     "care",
                     "do",
                     "did",
                     "decide",
                     "could",
                     "eat",
                     "does",
                     "doesnt",
                     "dont",
                     "should",
                     "was",
                     "would",
                     "wanna",
                     ]

transitiveVerbs = ["find",
                   "care",
                   "change",
                   "damn",
                   "do",
                   "did",
                   "decide",
                   "eat",
                   "does"
                   "doesnt",
                   "dont",
                   "said",
                   "says",
                   "searching",
                   "see",
                   "sells",
                   "serve",
                   "served",
                   "serves",
                   "serving",
                   "try",
                   "trying",
                   "want",
                   ]

auxiliaryVerbs = ["can",
                  "do",
                  "did",
                  "could",
                  "does",
                  "doesnt",
                  "dont",
                  "should",
                  "was",
                  "would",
                  ]

endFill = ["bye",
           ]

beginFill = ["ah",
            "uh",
            "um",
            "umh",
            "yes",
             ]

prepositions = ["about",
                "at",
                "beside",
                "for",
                "from",
                "then",
                "to",
                "with",
                ]

adverbs = ["alright",
           "fine",
           "again",
           "reasonably",
           "well",
           "so",
           ]

pronoun = ["something",
           "they",
           "you",
           "yourself",
           ]


questionWords = ["what",
                "whats",
           ]